DOMAIN = "cat_scale"

CONF_SOURCE_SENSOR = "source_sensor"
CONF_CAT_WEIGHT_THRESHOLD = "cat_weight_threshold"
CONF_MIN_PRESENCE_TIME = "min_presence_time"
CONF_LEAVE_TIMEOUT = "leave_timeout"

DEFAULT_NAME = "Cat Litter Detected Weight"
DEFAULT_CAT_WEIGHT_THRESHOLD = 1000
DEFAULT_MIN_PRESENCE_TIME = 4
DEFAULT_LEAVE_TIMEOUT = 120

AFTER_CAT_STANDARD_DEVIATION = 50