esphome:
  name: catscale
  friendly_name: Cat-scale

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
  - platform: web_server

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "catscale backup wifi"
    password: !secret backup_wifi_password

captive_portal:

button:
  - platform: safe_mode
    name: "Safe Mode Boot"
    entity_category: diagnostic
    id: catscale_safe_mode_boot

sensor:
  - platform: hx711
    name: "Cat Weight Sensor"
    dout_pin: GPIO32
    clk_pin: GPIO26

    gain: 128
    update_interval: 1s
    unit_of_measurement: g
    device_class: weight
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
          - 148937 -> 0 # Add own calibration here!
          - 2055181 -> 73900 # Add own calibration here!
      - clamp:
          min_value: -10000
          max_value: 200000
          ignore_out_of_range: true
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    entity_category: diagnostic
  - platform: internal_temperature
    entity_category: diagnostic
    name: "Internal Temperature"

switch:
  - platform: factory_reset
    name: "Restart with Factory Default Settings"
    entity_category: "diagnostic"

  - platform: restart
    name: "Restart"