name: HACS validation

on:
  push:
  pull_request:                  # ← add this
    branches: [main, beta]

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
